variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "aws_profile" {
  description = "AWS CLI profile to use for authentication"
  type        = string
  default     = "default"
}

variable "project_name" {
  description = "Short project name used in resource names"
  type        = string
  default     = "portfolio-site"
}

variable "domain_name" {
  description = "Primary domain name, e.g. example.com"
  type        = string
  default     = "example.com"
}

variable "cloudflare_account_id" {
  description = "Cloudflare account ID"
  type        = string
}

variable "cloudflare_zone_id" {
  description = "Cloudflare zone ID for the domain"
  type        = string
}

variable "access_allowed_emails" {
  description = "Email addresses allowed through Cloudflare Access while the site is private"
  type        = list(string)
  sensitive   = true
  default     = ["you@example.com"]
}

variable "site_bucket_name" {
  description = "Optional S3 bucket name override; if empty it will be autogenerated"
  type        = string
  default     = ""
}
